#!/bin/sh

echo "Starting the Test GLSC3D Library on your ubuntu!"

cd
WDR="GLSC3D_Working_Directory"
mkdir -p ${WDR}
cd ${WDR}

git --depth=1 clone https://github.com/GLSC3DProject/GLSC3D

cd GLSC3D
MyProject="MyProject"

if [ ! -s /usr/share/fonts/opentype/noto/NotoSansCJKjp-Regular.otf ]
then
sudo cp Install_file_and_script_and_fonts/NotoSansCJKjp-Regular.otf /usr/share/fonts/opentype/noto/
fi

mkdir ${MyProject}
cd ${MyProject}
cmake ../
make

echo "Check Samples"
cd ../Samples

echo "Do you want to run the Sample Program? (YES=1, NO=0)"
read TF

if [ $TF -eq 1 ]
then
	for x in Sample*.c
	do
		echo "Sample Program ${x%.c} running ... \n if you quit the program, push the ESC!"
		./${x%.c}
	done
fi

echo "Check Advanced"
cd ../Advanced

echo "Do you want to run the Advanced Program? (YES=1, NO=0)"
read TF
if [ $TF -eq 0 ]
then
echo "Successfully Done!!"
echo "Next step is \"3_Install_GLSC3D_on_your_ubuntu\""
exit
fi

if [ $TF -eq 1 ]
then
for x in *.c
do
	echo "Sample Program ${x%.c} running ... \n if you quit the program, push the ESC!"
	./${x%.c}
done

for x in *.cpp
do
	echo "Sample Program ${x%.cpp} running ... \n if you quit the program, push the ESC!"
	./${x%.cpp}
done
fi

echo "Successfully Done!!"
echo "Next step is \"3_Install_GLSC3D_on_your_ubuntu\""


