#!/bin/sh

#anyway install all library
sudo port -N install libsdl2 cmake libpng freetype

InstallCommand=""

comtemp="cmake"
echo "Checking $comtemp...."
if type $comtemp > /dev/null 2>&1
then
echo "$comtemp is installed"
else
echo "$comtemp is not installed"
InstallCommand="${InstallCommand} $comtemp"
fi

comtemp="libpng"
echo "Checking $comtemp...."
if type "libpng-config" > /dev/null 2>&1
then
echo "$comtemp is installed"
else
echo "$comtemp is not installed"
InstallCommand="${InstallCommand} $comtemp"
fi

comtemp="libfreetype"
echo "Checking $comtemp...."
libfreetype_existence=`port list | grep "freetype "`
if [ ${#libfreetype_existence} -gt 0 ]
then
echo "$comtemp is installed"
else
echo "$comtemp is not installed"
InstallCommand="${InstallCommand} $comtemp"
fi

comtemp="libsdl2"
echo "Checking $comtemp...."
sdl_existence=`port list | grep "libsdl2 "`

if [ ${#sdl_existence} -gt 0 ]
then
echo "$comtemp is installed"
else
echo "$comtemp is not installed"
InstallCommand="${InstallCommand} $comtemp"
fi

if [ ${#InstallCommand} -gt 0 ]
then
	echo "Error Occurred! Please again this script..."
else
	echo "Next step is \"3_Test_GLSC3D_on_mac\""
fi
